### ISSUE TITLE
Photos associate with different projects and maps than they are saved to

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#1]
Replicate this:
1. Use in-app camera to take photo.
2. Using drop-down menu, save photo to Free Obs, Signs of Spring, Watch Your Waterway, or Runoff Rundown.
3. Then go to Projects on the app OR the Explore pin to see where your photo is actually saved.
4. There seems to be a pattern of incorrect saving within the app:

Free Obs goes to Red Mountain 
Signs of Spring goes to Native or Not
Watch Your Waterway goes to Free Obs
Runoff Rundown goes to Tracks

**Comment by abhinay-balusu** [comment]
working fine with the new version, if encountered the same issue with the new build please let me know
