### ISSUE TITLE
Crashed while submitting observation

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#11]
Daniel is using iOS 10 beta 5 on an iPhone 6+. Reported a crash while submitting observation around 11 today. I could not replicate; may be related to beta version? Or to Travis making database change to Maryland projects at that moment? At any rate, the photo did not make it to the website.

![crashed while submitting observation](https://cloud.githubusercontent.com/assets/21040279/17706914/f1feb5da-63ab-11e6-8fff-1630d802c497.PNG)

**Comment by Kazjon** [comment]
Confirmed to occur on 9.3.2 -- not (only) an iOS 10 issue.

**Comment by maryloumaher** [comment]
I replicated this on my iphone, testflight v 1.7 and Ios 9.3.2, iphone 6s

**Comment by abhinay-balusu** [comment]
Unable to replicate this issue, submitted several observations
