### ISSUE TITLE
List of projects initially displayed doesn't map to list to which user may contribute

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#12]
Thinking from new user perspective. Screen 1 is what I see when I look at Projects. Screen 2 is the list of my local projects--the only places where I can submit. I discover Screen 2 only after I have taken a photo and am looking to save it.  Seems like there should be some organization provided on Projects list so I know ahead of time which projects are available to local user. Can projects on Screen 1 be organized or categorized in some way to convey this? 
![project list](https://cloud.githubusercontent.com/assets/21040279/17732250/da120a2e-643e-11e6-8fb7-5e73096a58a0.JPG)
![save to](https://cloud.githubusercontent.com/assets/21040279/17732249/da0eed08-643e-11e6-94ad-fea4a2239543.JPG)

**Comment by carolboston2** [comment]
The way this is done on the website (left side of Projects page) would be a good model for app too: **Projects at Anacostia**
A
B
C
**All Projects**
D
E
F

**Comment by maryloumaher** [comment]
A simple fix for this problem is to let anyone submit to any project now, rather than only list the projects associated with their affiliation. 
I like Carol's suggestion that the projects list include the site name for each project.

**Comment by Kazjon** [comment]
This seems closely related to #3 -- which is fundamentally about what projects are open or closed.

**Comment by Kazjon** [comment]
This relates to a much more complex design issue about site visibility, non-site users, and multi-site users.  We're going to have to leave that discussion to later.  For now, though, we need to decide to either filter neither of these screens or filter both of them.

**Comment by maryloumaher** [comment]
Decision for now is to show all projects on both screens. Revisit after the launch.

**Comment by WildWeazel** [comment]
see also https://github.com/naturenet/naturenet-android-app/issues/43
