### ISSUE TITLE
[UX] "Where is it" text box usability

### ISSUE THREAD

**Issue by WildWeazel** [naturenet/naturenet_ios#14]
The label is not visible, at least on iPad. It should say "Where is it?" in or before the box. Once given focus the keyboard cannot be dismissed. (workaround: select the description, then dismiss)

**Comment by maryloumaher** [comment]
I tried to add text to the where is it box on the ios app and the keyboard obscured the text entry. When finished, I clicked Done but the keyboard did not go away. Then I selected Send and the app crashed.

**Comment by Kazjon** [comment]
The crash-on-send is related to #11
