### ISSUE TITLE
Put Camera and Design Idea Icons on bottom of specific Project pages

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#2]
Right now, the icons for taking photo or adding design ideas live on the bottom of the Project Page only.

They would serve best if they were located (or also located) on each Project page, e.g., Watch Your Waterway, Red Mountain, Signs of Spring, etc. so people know what to do from within the project.

**Comment by abhinay-balusu** [comment]
Added camera and design idea buttons at the bottom of the specific projects page
