### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by wambeere** [naturenet/naturenet_ios#21]
I see the link for forgot password but clicking on it takes me nowhere

**Comment by WildWeazel** [comment]
Does anything happen? It's supposed to send you an email but there should be an alert to say what happened.

What version of phone & iOS are you using?

**Comment by abhinay-balusu** [comment]
Which build you are testing?

**Comment by wambeere** [comment]
OK, so just FYI, today password reset worked!
Thanks,
Liz

Elizabeth Muthoni Warrick
PhD Candidate. 
iSchool & Human Computer interaction Lab (HCiL).
University of Maryland. 
“I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.” Maya Angelou
