### ISSUE TITLE
Delay in notification after successful post

### ISSUE THREAD

**Issue by wambeere** [naturenet/naturenet_ios#24]
A few times, I've made two posts of the same observation in error--by clicking 'send' two times. I click 'send' a second time because I think that the first time did not register (nothing seems to be happening).  And then after a pause magically a message appears saying that my observation has been recorded (or sent, I forget the exact wording).  I am worried about the length of that pause between me hitting 'send' and the magical notice telling me I've been successful.

**Comment by WildWeazel** [comment]
Uploading the image does take some time, so the app can't confirm right away. It does need better feedback that the upload is in progress and/or delayed because of the network.
