### ISSUE TITLE
After observation submitted, going back to Explore and clicking on pin =crash

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#25]
Borrowed Jenny's phone on waterfront yesterday. So  these were Jenny photos from  9/14 midday of drainage ditches saved under Runoff Rundown and Watch Your Waterways. They saved successfully and showed up as new pins in the Bladensburg location under Explore. BUT, attempting to click on the new pins caused crashes 3 times.

**Comment by abhinay-balusu** [comment]
Unable to replicate this issue. 
Tested on several devices, @carolboston2  can you please specify on which Testflight version you got this issue
