### ISSUE TITLE
autosaved login credentials

### ISSUE THREAD

**Issue by sabdella** [naturenet/naturenet_ios#26]
Pepe once used my phone to login, I had been using the app and force stopping it several times after that. since today noticed that it was logged in with his credentials all these days. Should not force stopping logged me off? I do not remember ever asking the app to save the credentials and used to think I am using the app without logging in.

**Comment by abhinay-balusu** [comment]
working on it as this one is for future enhancement, Removing session and force logout on day change

**Comment by abhinay-balusu** [comment]
Fixed in af08d73033d05fdadc329cc8ec2b9dc41ad9d7bb
