### ISSUE TITLE
Comments are shown sporadically 

### ISSUE THREAD

**Issue by ghost** [naturenet/naturenet_ios#38]
![img_0267](https://cloud.githubusercontent.com/assets/8703780/19777913/96d5adfc-9c37-11e6-8a9d-e23589e87006.PNG)
![image2](https://cloud.githubusercontent.com/assets/8703780/19777911/96d3106a-9c37-11e6-87c4-dd25c10ad394.PNG)
![img_0269](https://cloud.githubusercontent.com/assets/8703780/19777912/96d39b98-9c37-11e6-883b-e8e2ed719b1f.PNG)

When trying to submit a comment to the comment section of a photo, you receive an alert. This should be changed to your comment appearing on the comment section similar to an Iphone message. The comment post process looks exactly like the Iphone message interface. Intuitively I assumed it was going to behave in that way. After posting the comment I could not see my comment even though it alerted me that it was posted. After posting it again I noticed duplicate comments, with the comment at the bottom not being visible.

**Comment by WildWeazel** [comment]
see #44
