### ISSUE TITLE
Unable to submit DESIGN IDEAS

### ISSUE THREAD

**Issue by tangc88** [naturenet/naturenet_ios#45]
Completely unsure of where or how to submit a design idea. There is no logical button to select. There is already a list of design ideas posted, so I know that its possible. I am currently on an iPhone 6s running iOS 10.0.2.
![img_3077](https://cloud.githubusercontent.com/assets/16884081/19864958/f27ac6d0-9f5f-11e6-9bef-67ac64e3c7df.PNG)

**Comment by WildWeazel** [comment]
#43
