### ISSUE TITLE
iPhone 6 Plus, iOS 10.0.1 - Can't take a picture using the camera

### ISSUE THREAD

**Issue by debolt** [naturenet/naturenet_ios#47]
So I have an issue where I try and click to take a picture the app crashes
1) Tap Explore on side bar
2) Tapped Camera Icon
3) Tap Camera
4) App crashes after the camera pulls up - every time

As far as I know I am unable to take a photo or add one from the gallery in this app due to it crashing whenever I tried and perform and action with the camera/photo. I am on WiFi and have location services turned on. I saw that this was an issue with android and maybe it could have transferred to iOS 10. Also the alignment of the camera app gets up in the space of the status bar on this iPhone.

![unnamed](https://cloud.githubusercontent.com/assets/11318969/19866185/bf571e52-9f64-11e6-9ca6-6cd34d4c2f76.png)
****this picture is of the view I get of the camera before the app crashes.**
*let me know if you can't see the picture, the upload link for it looks weird.

**Comment by WildWeazel** [comment]
#41
