### ISSUE TITLE
[Nav] After "Alert: Comment Posted Successfully," send user back to main screen, not back to posted comment

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#5]
Example:
1. Left a comment on Travis's Thursday/What is this tree? photo under Free Observation.
2. Typed in Magnolia? and hit Send.
3. Got an Alert: Comment Posted Successfully.
4. Was returned to comment box with the word Magnolia? still showing. 
5. User could get in a loop of resending and getting alert again. Better to send them back to Projects: Free Observation.

**Comment by maryloumaher** [comment]
Let's try to replicate this and add more discussion.

**Comment by abhinay-balusu** [comment]
Instead of going back to home page, i just cleared the comment text field and comments are also updated
