### ISSUE TITLE
Crashes for iPhone 6 IOS 9.3.4 when clicking "use photo" 

### ISSUE THREAD

**Issue by No-Doy** [naturenet/naturenet_ios#50]
Crashes after I take a picture!
I am using an iPhone 6 Version 9.3.4. 
I tapped the camera logo and it was able to access my camera. 
After it accessed my camera the application asked me if I wanted to use my “camera” or “gallery” to upload a photo. 
At first I clicked “camera” and took a picture. 
After clicking “use photo” the application closed on itself.
I tried serval times with WiFi on and off, and my battery saving mode on and off. Every time after clicking “use photo” the application crashed! It did every time even for uploading pictures from the “gallery” option.

Also, trying to add a post on the "Drownspouts" by uploading from "camera" or "gallery" crashes the application.

- Brian Alfano
[crash.MOV.zip](https://github.com/naturenet/naturenet_ios/files/562970/crash.MOV.zip)

**Comment by WildWeazel** [comment]
#41
