### ISSUE TITLE
Cannot leave a contribution on Design Ideas

### ISSUE THREAD

**Issue by Aycel07** [naturenet/naturenet_ios#51]
I am using an iPhone 6 running iOS 10.0.2 and was within wifi range when the issue arose. 

The issue I found is more of a design issue within the app. When trying to add a contribution for the Design Ideas, I could not find the button that would allow me to post my own contribution. Maybe it's there and it's just not obvious to me? I am not sure. 
The way I got to the screen was by going to the side menu, then clicking on 'Design Ideas' which lead me to the screen of recent contributions but could not find the button that would allow me to post my own contribution. There was no error message. 
![img_1293](https://cloud.githubusercontent.com/assets/17656676/19877767/af379270-9fa7-11e6-806d-e7054c58b6ce.jpg)

If I was able to make a contribution it would still be on design. Most of the app was really simple to use but one thing I would suggest would be to create a 'bubble' for users when adding a comment. That way the user can view the whole comment before sending/posting it, instead of having to scroll left and right to read the whole message before sending it. A user should be able to easily view and read their message incase they need or want to make changes before they submit it. 

![img_1294](https://cloud.githubusercontent.com/assets/17656676/19877772/bb252d86-9fa7-11e6-90dd-d90c428c4704.jpg)

**Comment by WildWeazel** [comment]
#43
