### ISSUE TITLE
Log out button too close to other features

### ISSUE THREAD

**Issue by nikamcgill** [naturenet/naturenet_ios#53]
Upon clicking the sidebar in the upper left corner to view the drop-down list of options, I keep accidentally signing out when trying to click Communities or swipe to a different screen. It would be helpful if the Logout button were somewhere further from the others, such as at the bottom of the screen or in a corner somewhere. It might also be nice if the app remembered my email so I didn't have to type it in each time I wish to log back in. Using iPhone app, iOS 10.1.1

![img_5025](https://cloud.githubusercontent.com/assets/11895036/19880304/93e714ea-9fc1-11e6-9e3e-d89427c4c948.PNG)

**Comment by abhinay-balusu** [comment]
added some white space above logout button
