### ISSUE TITLE
Can't submit new Design Idea from the "Design Ideas" tab (iOS)

### ISSUE THREAD

**Issue by TRianR** [naturenet/naturenet_ios#55]
When on the "Design Ideas" tab I could not submit a new idea of my own. I was able to solve this issue however by going to the "Communities" tab and submitting it from there. I noticed you could also do this from the "Projects" tab, so a simple fix of adding the option to submit a new design idea in the "Design Ideas" tab will fix this.

Issue occurred on my iPhone running iOS 10.1.1 while I was at home on wifi.

Here are two images, one showing the way I solved my issue and one showing the issue I faced. 

![img_5688](https://cloud.githubusercontent.com/assets/11948770/19880544/da2054ec-9fc3-11e6-8af0-c5b20caab880.PNG)
![img_5689](https://cloud.githubusercontent.com/assets/11948770/19880545/da207666-9fc3-11e6-9c11-a434d1bac47c.PNG)

**Comment by WildWeazel** [comment]
#43
