### ISSUE TITLE
Added Comment to Design Challenge; Kicked Out of App

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#7]
To replicate:
1. Go to Design Challenge/NN/June 10/What optional demo.
2. Add a comment.
3. Hit Send
4. See if you are sent all the way back to the iOS home screen.
   (comment was successfully posted to the website, btw but is NOT visible on the app)
5. Go to Design Challenge/Mary Lou/June 2/I would like to be able to tag people.
6. Add a comment.
7. Hit Send.
8. See if you are sent all the way back to the iOS screen
   (comment was successfully posted to the website, btw, but is NOT visible on the app)

**Comment by WildWeazel** [comment]
@carolboston2 was this on an iPad?

**Comment by carolboston2** [comment]
Yes

**Comment by abhinay-balusu** [comment]
working fine in ipad, even rectified the layout issues
