### ISSUE TITLE
Remove green JOIN option once user has downloaded and joined?

### ISSUE THREAD

**Issue by carolboston2** [naturenet/naturenet_ios#8]
![remove join option after joining](https://cloud.githubusercontent.com/assets/21040279/17706370/be97044c-63a9-11e6-83e7-5e4380e86eea.PNG)

Once they have downloaded and set up account, shouldn't the options be to Sign in or Reset Password only?

**Comment by Kazjon** [comment]
This this part of a larger re-design of this splash page to match our new website landing page.

**Comment by WildWeazel** [comment]
This screen will be changing but Abhinay already had the button behavior done
